name: Deploy para Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v3

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: curriculotesteazurehost
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
